package org.icube.hyrsmart.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Admin extends AbsoluteLayout {
	protected Label lbl_adminname;
	protected Label lbl_logo;
	protected TabSheet tab_admin;
	protected Label lbl_adminsummary;
	protected Label lbl_adminview;
	protected TextField txt_allowednum;
	protected TextField txt_completednum;
	protected TextField txt_exitednum;
	protected TextField txt_live;
	protected TextField txt_balance;
	protected TextField txt_allowedlbl;
	protected TextField txt_completedlbl;
	protected Grid grd_testdetails;

	public Admin() {
		Design.read(this);
	}
}
