package org.icube.hyrsmart.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SuperAdmin extends AbsoluteLayout {
	protected Label lbl_logo2;
	protected Label lbl_adminname2;
	protected VerticalLayout vlyt_summary;
	protected HorizontalLayout hzt_count;
	protected TextField txt_allowed_count;
	protected TextField txt_completed_count;
	protected TextField txt_exited_count;
	protected TextField txt_live_count;
	protected TextField txt_balance_count;
	protected HorizontalLayout htz_label;
	protected TextField txt_allowed;
	protected TextField txt_completed;
	protected TextField txt_exited;
	protected TextField txt_live;
	protected TextField txt_balance;
	protected Grid grd_summary;
	protected VerticalLayout vlyt_view;
	protected NativeSelect dpn_recruiterlogin;
	protected DateField dte_fromdate;
	protected TextField txt_search;
	protected DateField dte_todate;
	protected NativeSelect dpn_status;
	protected Button btn_reset;
	protected Button btn_submit;
	protected Label lbl_totalres;
	protected NativeSelect dpn_sorttest;
	protected Button btn_exportcsv;
	protected Button btn_exportpdf;
	protected Grid grd_testdetails;

	public SuperAdmin() {
		Design.read(this);
	}
}
