package org.icube.hyrsmart.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Test extends AbsoluteLayout {
	protected Label lbl_adminname;
	protected Label lbl_logo;
	protected VerticalLayout vtly_adminview;
	protected NativeSelect dpn_recruiterlogin;
	protected DateField dte_fromdate;
	protected TextField txt_search;
	protected DateField dte_todate;
	protected NativeSelect dpn_status;
	protected Button btn_reset;
	protected Button btn_submit;
	protected Label lbl_totalres;
	protected NativeSelect dpn_sorttest;
	protected Button btn_exportcsv;
	protected Button btn_exportpdf;
	protected Grid grd_testdetails;

	public Test() {
		Design.read(this);
	}
}
