package org.icube.hyrsmart.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Test extends AbsoluteLayout {
	protected Label lbl_logo;
	protected VerticalLayout vtly_welcome;
	protected VerticalLayout vtly_registration;
	protected Label lbl_personalinfo;
	protected Label lbl_name;
	protected TextField txt_firstname;
	protected TextField txt_middlename;
	protected TextField txt_lastname;
	protected Label lbl_email;
	protected TextField txt_email;
	protected Label lbl_mobile;
	protected TextField txt_mobile;
	protected Label lbl_degree;
	protected TextField txt_degree;
	protected Label lbl_stream;
	protected TextField txt_stream;
	protected Label lbl_city;
	protected NativeSelect dpn_city;
	protected Label lbl_aadharno;
	protected TextField txt_stream2;
	protected Button btn_cancel;
	protected Button btn_continue;
	protected VerticalLayout vtly_instructions;
	protected VerticalLayout vtly_test;
	protected Label lbl_quesno;
	protected Label lbl_ques;
	protected VerticalLayout vtly_thankyou;
	protected NativeSelect dpn_selectlang;

	public Test() {
		Design.read(this);
	}
}
