package org.icube.hyrsmart.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CandidateProfile extends AbsoluteLayout {
	protected Label lbl_logo;
	protected Label lbl_profile;
	protected Label lbl_name;
	protected Label lbl_namevalue;
	protected Label lbl_id;
	protected Label lbl_idvalue;
	protected Label lbl_mobile;
	protected Label lbl_mobilevalue;
	protected Label lbl_email;
	protected Label lbl_emailvalue;
	protected Label lbl_degree;
	protected Label lbl_degreevalue;
	protected Label lbl_stream;
	protected Label lbl_streamvalue;
	protected Label lbl_score;
	protected Label lbl_scorevalue;
	protected Button btn_print;
	protected Button btn_save;

	public CandidateProfile() {
		Design.read(this);
	}
}
