package org.icube.hyrsmart.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Test extends AbsoluteLayout {
	protected Label lbl_logo;
	protected TabSheet tbs_test;
	protected VerticalLayout vtly_welcome;
	protected Label lbl_welcome;
	protected OptionGroup opg_agreement;
	protected Button btn_startNewTest;
	protected Button btn_signout;
	protected VerticalLayout vtly_registration;
	protected Label lbl_personalinfo;
	protected Label lbl_name;
	protected TextField txt_firstname;
	protected TextField txt_middlename;
	protected TextField txt_lastname;
	protected Label lbl_email;
	protected TextField txt_email;
	protected Label lbl_mobile;
	protected TextField txt_mobile;
	protected Label lbl_degree;
	protected TextField txt_degree;
	protected Label lbl_stream;
	protected TextField txt_stream;
	protected Label lbl_city;
	protected NativeSelect dpn_city;
	protected Label lbl_aadharno;
	protected TextField txt_stream2;
	protected Button btn_cancel;
	protected Button btn_continue;
	protected VerticalLayout vtly_instructions;
	protected Label lbl_instructions;
	protected VerticalLayout vtly_test;
	protected VerticalLayout vtly_quescat1;
	protected Label lbl_quesno1;
	protected Label lbl_ques1;
	protected Label lbl_subques1;
	protected OptionGroup opg_subquesgp1;
	protected Label lbl_subques2;
	protected OptionGroup opg_subquesgp2;
	protected Label lbl_subques3;
	protected OptionGroup opg_subquesgp3;
	protected Label lbl_subques4;
	protected OptionGroup opg_subquesgp4;
	protected Label lbl_subques5;
	protected OptionGroup opg_subquesgp5;
	protected Button btn_testprev1;
	protected Button btn_testnext1;
	protected VerticalLayout vtly_quescat2;
	protected Label lbl_quesno2;
	protected Label lbl_ques2;
	protected Label lbl_subques1forques2;
	protected OptionGroup opg_subques1forques2gp1;
	protected Button btn_testprev2;
	protected Button btn_testnext2;
	protected VerticalLayout vtly_quescat3;
	protected Label lbl_quesno3;
	protected Label lbl_ques3;
	protected Image img_quesimg;
	protected Label lbl_subques1forques3;
	protected OptionGroup opg_subques1forques3gp1;
	protected Button btn_testprev3;
	protected Button btn_testfinish1;
	protected VerticalLayout vtly_thankyou;
	protected Label lbl_thankyou;
	protected NativeSelect dpn_selectlang;

	public Test() {
		Design.read(this);
	}
}
